# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formActor.ui'
#
# Created: Mon Jul 14 13:45:28 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FormularioActor(object):
    def setupUi(self, FormularioActor):
        FormularioActor.setObjectName("FormularioActor")
        FormularioActor.resize(450, 510)
        FormularioActor.setMinimumSize(QtCore.QSize(450, 510))
        FormularioActor.setMaximumSize(QtCore.QSize(450, 510))
        self.verticalLayout = QtGui.QVBoxLayout(FormularioActor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtGui.QLabel(FormularioActor)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.widget = QtGui.QWidget(FormularioActor)
        self.widget.setMaximumSize(QtCore.QSize(432, 86))
        self.widget.setObjectName("widget")
        self.formLayout_3 = QtGui.QFormLayout(self.widget)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.nombreLineEdit = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombreLineEdit.sizePolicy().hasHeightForWidth())
        self.nombreLineEdit.setSizePolicy(sizePolicy)
        self.nombreLineEdit.setMinimumSize(QtCore.QSize(328, 0))
        self.nombreLineEdit.setMaximumSize(QtCore.QSize(328, 16777215))
        self.nombreLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.nombreLineEdit.setObjectName("nombreLineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.nombreLineEdit)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.widget_8 = QtGui.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.diaSpinBox = QtGui.QSpinBox(self.widget_8)
        self.diaSpinBox.setMinimumSize(QtCore.QSize(50, 31))
        self.diaSpinBox.setMaximumSize(QtCore.QSize(50, 31))
        self.diaSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.diaSpinBox.setMinimum(1)
        self.diaSpinBox.setMaximum(31)
        self.diaSpinBox.setProperty("value", 1)
        self.diaSpinBox.setObjectName("diaSpinBox")
        self.horizontalLayout_6.addWidget(self.diaSpinBox)
        self.mesComboBox = QtGui.QComboBox(self.widget_8)
        self.mesComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.mesComboBox.setMaximumSize(QtCore.QSize(120, 31))
        self.mesComboBox.setObjectName("mesComboBox")
        self.horizontalLayout_6.addWidget(self.mesComboBox)
        self.yearSpinBox = QtGui.QSpinBox(self.widget_8)
        self.yearSpinBox.setMinimumSize(QtCore.QSize(63, 31))
        self.yearSpinBox.setMaximumSize(QtCore.QSize(63, 31))
        self.yearSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.yearSpinBox.setMinimum(1500)
        self.yearSpinBox.setMaximum(2014)
        self.yearSpinBox.setProperty("value", 2014)
        self.yearSpinBox.setObjectName("yearSpinBox")
        self.horizontalLayout_6.addWidget(self.yearSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.widget_8)
        self.verticalLayout.addWidget(self.widget)
        self.widget_4 = QtGui.QWidget(FormularioActor)
        self.widget_4.setMinimumSize(QtCore.QSize(432, 277))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_6 = QtGui.QWidget(self.widget_4)
        self.widget_6.setMinimumSize(QtCore.QSize(169, 259))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtGui.QWidget(self.widget_6)
        self.widget_3.setObjectName("widget_3")
        self.formLayout = QtGui.QFormLayout(self.widget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.masculinoRadioButton = QtGui.QRadioButton(self.widget_3)
        self.masculinoRadioButton.setObjectName("masculinoRadioButton")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.masculinoRadioButton)
        self.femeninoRadioButton = QtGui.QRadioButton(self.widget_3)
        self.femeninoRadioButton.setObjectName("femeninoRadioButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.femeninoRadioButton)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_7 = QtGui.QWidget(self.widget_6)
        self.widget_7.setMaximumSize(QtCore.QSize(213, 104))
        self.widget_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nuevaImagenButton = QtGui.QPushButton(self.widget_7)
        self.nuevaImagenButton.setMaximumSize(QtCore.QSize(45, 45))
        self.nuevaImagenButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgInterfaz/buscarImagen1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nuevaImagenButton.setIcon(icon)
        self.nuevaImagenButton.setIconSize(QtCore.QSize(30, 30))
        self.nuevaImagenButton.setObjectName("nuevaImagenButton")
        self.verticalLayout_4.addWidget(self.nuevaImagenButton)
        self.borrarImagenButton = QtGui.QPushButton(self.widget_7)
        self.borrarImagenButton.setMaximumSize(QtCore.QSize(45, 45))
        self.borrarImagenButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgInterfaz/eliminarImagen1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.borrarImagenButton.setIcon(icon1)
        self.borrarImagenButton.setIconSize(QtCore.QSize(30, 30))
        self.borrarImagenButton.setObjectName("borrarImagenButton")
        self.verticalLayout_4.addWidget(self.borrarImagenButton)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_4.addWidget(self.widget_6)
        self.groupBox = QtGui.QGroupBox(self.widget_4)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(-1, 6, 9, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imagenActorLabel = QtGui.QLabel(self.groupBox)
        self.imagenActorLabel.setMinimumSize(QtCore.QSize(200, 230))
        self.imagenActorLabel.setMaximumSize(QtCore.QSize(200, 230))
        self.imagenActorLabel.setText("")
        self.imagenActorLabel.setScaledContents(True)
        self.imagenActorLabel.setObjectName("imagenActorLabel")
        self.verticalLayout_3.addWidget(self.imagenActorLabel)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(FormularioActor)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 49))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.guardarButton = QtGui.QPushButton(self.widget_5)
        self.guardarButton.setObjectName("guardarButton")
        self.horizontalLayout_3.addWidget(self.guardarButton)
        spacerItem3 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cancelarButton = QtGui.QPushButton(self.widget_5)
        self.cancelarButton.setObjectName("cancelarButton")
        self.horizontalLayout_3.addWidget(self.cancelarButton)
        spacerItem4 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_5)

        self.retranslateUi(FormularioActor)
        QtCore.QObject.connect(self.cancelarButton, QtCore.SIGNAL("clicked()"), FormularioActor.close)
        QtCore.QMetaObject.connectSlotsByName(FormularioActor)
        FormularioActor.setTabOrder(self.nombreLineEdit, self.diaSpinBox)
        FormularioActor.setTabOrder(self.diaSpinBox, self.mesComboBox)
        FormularioActor.setTabOrder(self.mesComboBox, self.yearSpinBox)
        FormularioActor.setTabOrder(self.yearSpinBox, self.femeninoRadioButton)
        FormularioActor.setTabOrder(self.femeninoRadioButton, self.masculinoRadioButton)
        FormularioActor.setTabOrder(self.masculinoRadioButton, self.nuevaImagenButton)
        FormularioActor.setTabOrder(self.nuevaImagenButton, self.borrarImagenButton)
        FormularioActor.setTabOrder(self.borrarImagenButton, self.guardarButton)
        FormularioActor.setTabOrder(self.guardarButton, self.cancelarButton)

    def retranslateUi(self, FormularioActor):
        FormularioActor.setWindowTitle(QtGui.QApplication.translate("FormularioActor", "Nuevo Actor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormularioActor", "Complete con la información requerida. Cuando este seguro guarde lo que ingreso.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormularioActor", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormularioActor", "Cumpleaños", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormularioActor", "Sexo", None, QtGui.QApplication.UnicodeUTF8))
        self.masculinoRadioButton.setText(QtGui.QApplication.translate("FormularioActor", "Masculino", None, QtGui.QApplication.UnicodeUTF8))
        self.femeninoRadioButton.setText(QtGui.QApplication.translate("FormularioActor", "Femenino", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormularioActor", "Fotografía", None, QtGui.QApplication.UnicodeUTF8))
        self.guardarButton.setText(QtGui.QApplication.translate("FormularioActor", "&Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelarButton.setText(QtGui.QApplication.translate("FormularioActor", "&Cancelar", None, QtGui.QApplication.UnicodeUTF8))

