# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formPelicula.ui'
#
# Created: Sat Jul 12 02:31:35 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FormularioPelicula(object):
    def setupUi(self, FormularioPelicula):
        FormularioPelicula.setObjectName("FormularioPelicula")
        FormularioPelicula.resize(450, 509)
        FormularioPelicula.setMinimumSize(QtCore.QSize(450, 0))
        FormularioPelicula.setMaximumSize(QtCore.QSize(450, 509))
        self.verticalLayout_6 = QtGui.QVBoxLayout(FormularioPelicula)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtGui.QStackedWidget(FormularioPelicula)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.datosPelicula = QtGui.QWidget()
        self.datosPelicula.setEnabled(True)
        self.datosPelicula.setObjectName("datosPelicula")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.datosPelicula)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtGui.QLabel(self.datosPelicula)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.widget = QtGui.QWidget(self.datosPelicula)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nombreLineEdit = QtGui.QLineEdit(self.widget)
        self.nombreLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.nombreLineEdit.setObjectName("nombreLineEdit")
        self.horizontalLayout.addWidget(self.nombreLineEdit)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_8 = QtGui.QWidget(self.datosPelicula)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_7 = QtGui.QWidget(self.widget_8)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtGui.QWidget(self.widget_7)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtGui.QFormLayout(self.widget_2)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(9)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.estrenoLineEdit = QtGui.QLineEdit(self.widget_2)
        self.estrenoLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.estrenoLineEdit.setObjectName("estrenoLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.estrenoLineEdit)
        self.label_4 = QtGui.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.directorLineEdit = QtGui.QLineEdit(self.widget_2)
        self.directorLineEdit.setObjectName("directorLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.directorLineEdit)
        self.label_5 = QtGui.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.paisLineEdit = QtGui.QLineEdit(self.widget_2)
        self.paisLineEdit.setObjectName("paisLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.paisLineEdit)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_6 = QtGui.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtGui.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.tramaPlainTextEdit = QtGui.QPlainTextEdit(self.widget_6)
        self.tramaPlainTextEdit.setObjectName("tramaPlainTextEdit")
        self.verticalLayout_3.addWidget(self.tramaPlainTextEdit)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.horizontalLayout_4.addWidget(self.widget_7)
        self.widget_5 = QtGui.QWidget(self.widget_8)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtGui.QWidget(self.widget_5)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.widget_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.line = QtGui.QFrame(self.widget_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.imagenLabel = QtGui.QLabel(self.widget_5)
        self.imagenLabel.setMinimumSize(QtCore.QSize(200, 240))
        self.imagenLabel.setMaximumSize(QtCore.QSize(200, 240))
        self.imagenLabel.setText("")
        self.imagenLabel.setPixmap(QtGui.QPixmap("ImgProductos/No Imagen.png"))
        self.imagenLabel.setScaledContents(True)
        self.imagenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imagenLabel.setWordWrap(False)
        self.imagenLabel.setOpenExternalLinks(False)
        self.imagenLabel.setObjectName("imagenLabel")
        self.verticalLayout_2.addWidget(self.imagenLabel)
        self.widget_4 = QtGui.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.nuevaImagenButton = QtGui.QPushButton(self.widget_4)
        self.nuevaImagenButton.setMaximumSize(QtCore.QSize(40, 40))
        self.nuevaImagenButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgInterfaz/buscarImagen1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nuevaImagenButton.setIcon(icon)
        self.nuevaImagenButton.setIconSize(QtCore.QSize(30, 30))
        self.nuevaImagenButton.setObjectName("nuevaImagenButton")
        self.horizontalLayout_3.addWidget(self.nuevaImagenButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.borrarImagenButton = QtGui.QPushButton(self.widget_4)
        self.borrarImagenButton.setMaximumSize(QtCore.QSize(40, 40))
        self.borrarImagenButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgInterfaz/eliminarImagen1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.borrarImagenButton.setIcon(icon1)
        self.borrarImagenButton.setIconSize(QtCore.QSize(30, 30))
        self.borrarImagenButton.setObjectName("borrarImagenButton")
        self.horizontalLayout_3.addWidget(self.borrarImagenButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.elencoButton = QtGui.QPushButton(self.widget_5)
        self.elencoButton.setObjectName("elencoButton")
        self.verticalLayout_2.addWidget(self.elencoButton)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.widget_8)
        self.widget_9 = QtGui.QWidget(self.datosPelicula)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.agregarButton = QtGui.QPushButton(self.widget_9)
        self.agregarButton.setObjectName("agregarButton")
        self.horizontalLayout_5.addWidget(self.agregarButton)
        spacerItem4 = QtGui.QSpacerItem(65, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.cancelarButton = QtGui.QPushButton(self.widget_9)
        self.cancelarButton.setObjectName("cancelarButton")
        self.horizontalLayout_5.addWidget(self.cancelarButton)
        spacerItem5 = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.widget_9)
        self.stackedWidget.addWidget(self.datosPelicula)
        self.elencoPelicula = QtGui.QWidget()
        self.elencoPelicula.setObjectName("elencoPelicula")
        self.verticalLayout = QtGui.QVBoxLayout(self.elencoPelicula)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.elencoPelicula)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.groupBox_4 = QtGui.QGroupBox(self.elencoPelicula)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.actoresComboBox = QtGui.QComboBox(self.groupBox_2)
        self.actoresComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.actoresComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.actoresComboBox.setObjectName("actoresComboBox")
        self.horizontalLayout_8.addWidget(self.actoresComboBox)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.rolLineEdit = QtGui.QLineEdit(self.groupBox)
        self.rolLineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.rolLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.rolLineEdit.setObjectName("rolLineEdit")
        self.horizontalLayout_6.addWidget(self.rolLineEdit)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.infoRolPlainTextEdit = QtGui.QPlainTextEdit(self.groupBox_3)
        self.infoRolPlainTextEdit.setMinimumSize(QtCore.QSize(250, 100))
        self.infoRolPlainTextEdit.setMaximumSize(QtCore.QSize(300, 100))
        self.infoRolPlainTextEdit.setObjectName("infoRolPlainTextEdit")
        self.horizontalLayout_9.addWidget(self.infoRolPlainTextEdit)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.widget_10 = QtGui.QWidget(self.elencoPelicula)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.grabarElencoButton = QtGui.QPushButton(self.widget_10)
        self.grabarElencoButton.setObjectName("grabarElencoButton")
        self.horizontalLayout_10.addWidget(self.grabarElencoButton)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.terminarElencoButton = QtGui.QPushButton(self.widget_10)
        self.terminarElencoButton.setObjectName("terminarElencoButton")
        self.horizontalLayout_10.addWidget(self.terminarElencoButton)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout.addWidget(self.widget_10)
        self.stackedWidget.addWidget(self.elencoPelicula)
        self.verticalLayout_6.addWidget(self.stackedWidget)

        self.retranslateUi(FormularioPelicula)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelarButton, QtCore.SIGNAL("clicked()"), FormularioPelicula.close)
        QtCore.QMetaObject.connectSlotsByName(FormularioPelicula)
        FormularioPelicula.setTabOrder(self.nombreLineEdit, self.estrenoLineEdit)
        FormularioPelicula.setTabOrder(self.estrenoLineEdit, self.directorLineEdit)
        FormularioPelicula.setTabOrder(self.directorLineEdit, self.paisLineEdit)
        FormularioPelicula.setTabOrder(self.paisLineEdit, self.tramaPlainTextEdit)
        FormularioPelicula.setTabOrder(self.tramaPlainTextEdit, self.nuevaImagenButton)
        FormularioPelicula.setTabOrder(self.nuevaImagenButton, self.borrarImagenButton)
        FormularioPelicula.setTabOrder(self.borrarImagenButton, self.elencoButton)
        FormularioPelicula.setTabOrder(self.elencoButton, self.actoresComboBox)
        FormularioPelicula.setTabOrder(self.actoresComboBox, self.rolLineEdit)
        FormularioPelicula.setTabOrder(self.rolLineEdit, self.infoRolPlainTextEdit)
        FormularioPelicula.setTabOrder(self.infoRolPlainTextEdit, self.grabarElencoButton)
        FormularioPelicula.setTabOrder(self.grabarElencoButton, self.terminarElencoButton)
        FormularioPelicula.setTabOrder(self.terminarElencoButton, self.agregarButton)
        FormularioPelicula.setTabOrder(self.agregarButton, self.cancelarButton)

    def retranslateUi(self, FormularioPelicula):
        FormularioPelicula.setWindowTitle(QtGui.QApplication.translate("FormularioPelicula", "Nueva Película", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormularioPelicula", "Complete el formulario y confirme para guardar los datos.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormularioPelicula", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormularioPelicula", "Año Estreno", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormularioPelicula", "Director", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormularioPelicula", "Pais", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormularioPelicula", "Trama", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FormularioPelicula", "Imagen:", None, QtGui.QApplication.UnicodeUTF8))
        self.nuevaImagenButton.setToolTip(QtGui.QApplication.translate("FormularioPelicula", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Añada una fotografía de la película</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Tamaño recomendado 200px x 240px o superior</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.borrarImagenButton.setToolTip(QtGui.QApplication.translate("FormularioPelicula", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Eliminar imagen</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.elencoButton.setText(QtGui.QApplication.translate("FormularioPelicula", "Modificar Elenco", None, QtGui.QApplication.UnicodeUTF8))
        self.agregarButton.setText(QtGui.QApplication.translate("FormularioPelicula", "&Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelarButton.setText(QtGui.QApplication.translate("FormularioPelicula", "&Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormularioPelicula", "<html><head/><body><p align=\"center\">Seleccione un actor, desígnele su rol y descríbalo previamente antes de grabar. Ya guardado el actor ingresado puede continuar añadiendo actores a la película tantas veces quiera. Cuando haya finalizado la asignación de roles presione terminar para continuar con en ingreso de la película.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("FormularioPelicula", "Elenco para ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FormularioPelicula", "Actor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormularioPelicula", "Rol del actor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("FormularioPelicula", "Descripción del rol", None, QtGui.QApplication.UnicodeUTF8))
        self.grabarElencoButton.setText(QtGui.QApplication.translate("FormularioPelicula", "&Grabar", None, QtGui.QApplication.UnicodeUTF8))
        self.terminarElencoButton.setText(QtGui.QApplication.translate("FormularioPelicula", "&Terminar", None, QtGui.QApplication.UnicodeUTF8))

